script:
  commands: list[command | pipeline]

pipeline:
  commands: list[command]

command:
  name: word
  prefix: list[redirection]
  suffix: list[word | redirection]

word:
  text: str
  expansion: list[list[int, int, str]]

redirection:
  file: str
  op: enum(<, <<, >, >>)
